/*
 * Native offline replay engine for the Bowie mag_fusion algorithm.
 *
 * Input is a tiny packed binary file generated by replay_firmware.py:
 *   header: "MFREPLAY", version, state_size, link, reserved
 *   record: kind, 3 pad bytes, index, BHI ticks, five float values
 *
 * It loads the exact mag_fusion_t snapshot recorded on the board and calls the
 * same mag_fusion.c functions in the same event order.  The output is a CSV
 * trace for comparison with the recorded firmware output.
 */

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "mag_fusion.h"

typedef struct __attribute__((packed)) replay_header {
    char magic[8];
    uint32_t version;
    uint32_t state_size;
    uint32_t link;
    uint32_t reserved;
} replay_header_t;

typedef struct __attribute__((packed)) replay_record {
    uint8_t kind;
    uint8_t pad[3];
    uint32_t index;
    uint64_t ts_ticks;
    float v[5];
} replay_record_t;

enum {
    REC_QUAT = 0,
    REC_MAG = 1,
    REC_GYRO = 2,
    REC_ACC = 3,
    REC_MAG2 = 4
};

int main(int argc, char **argv)
{
    FILE *in;
    FILE *out;
    replay_header_t header;
    replay_record_t rec;
    mag_fusion_t fusion;
    uint64_t seq = 0u;
    float last_q[4] = {1.0f, 0.0f, 0.0f, 0.0f};

    if (argc != 3) {
        fprintf(stderr, "usage: %s replay_input.bin replay_output.csv\n", argv[0]);
        return 2;
    }
    in = fopen(argv[1], "rb");
    if (!in) {
        perror("open input");
        return 3;
    }
    out = fopen(argv[2], "w");
    if (!out) {
        perror("open output");
        fclose(in);
        return 3;
    }

    if (fread(&header, sizeof(header), 1, in) != 1 ||
        memcmp(header.magic, "MFREPLAY", 8) != 0 ||
        header.version != 1u ||
        header.state_size != sizeof(mag_fusion_t)) {
        fprintf(stderr, "bad replay header or state size mismatch (got %u, expected %u)\n",
                (unsigned)header.state_size, (unsigned)sizeof(mag_fusion_t));
        fclose(in);
        fclose(out);
        return 4;
    }
    if (fread(&fusion, 1, sizeof(fusion), in) != sizeof(fusion)) {
        fprintf(stderr, "truncated fusion state\n");
        fclose(in);
        fclose(out);
        return 4;
    }

    fprintf(out,
            "seq,index,kind,ts_ticks,yaw_corr_deg,datum_deg,accuracy,status,"
            "yaw_valid,rejecting,hard_event,weight,out_qw,out_qx,out_qy,out_qz\n");

    while (fread(&rec, sizeof(rec), 1, in) == 1) {
        float mag_out[3] = {0.0f, 0.0f, 0.0f};
        float q[4] = {1.0f, 0.0f, 0.0f, 0.0f};

        if (rec.kind == REC_QUAT) {
            /* CSV/record order is x,y,z,w; mag_fusion uses w,x,y,z. */
            q[0] = rec.v[3];
            q[1] = rec.v[0];
            q[2] = rec.v[1];
            q[3] = rec.v[2];
            (void)mag_fusion_on_quat(&fusion, rec.ts_ticks, q);
            memcpy(last_q, q, sizeof(last_q));
        } else if (rec.kind == REC_MAG) {
            (void)mag_fusion_on_mag(&fusion, rec.v, mag_out);
        } else if (rec.kind == REC_GYRO) {
            mag_fusion_on_gyro(&fusion, rec.v);
        } else if (rec.kind == REC_MAG2) {
            (void)mag_fusion_on_mag2(&fusion, rec.v, NULL);
        } else if (rec.kind == REC_ACC) {
            /* Reserved for future static/ZUPT gates. */
        } else {
            fprintf(stderr, "unknown record kind %u\n", (unsigned)rec.kind);
            fclose(in);
            fclose(out);
            return 5;
        }

        fprintf(out,
                "%I64u,%u,%u,%I64u,%.9f,%.9f,%.9f,%u,%u,%u,%u,%.9f,"
                "%.9f,%.9f,%.9f,%.9f\n",
                (unsigned long long)seq++,
                (unsigned)rec.index,
                (unsigned)rec.kind,
                (unsigned long long)rec.ts_ticks,
                (double)mag_fusion_yaw_corr_deg(&fusion),
                (double)mag_fusion_datum_deg(&fusion),
                (double)mag_fusion_accuracy(&fusion),
                (unsigned)fusion.status,
                (unsigned)fusion.yaw_valid,
                (unsigned)fusion.rejecting,
                (unsigned)fusion.hard_event,
                (double)fusion.weight,
                (double)last_q[0], (double)last_q[1], (double)last_q[2], (double)last_q[3]);
    }

    fclose(in);
    fclose(out);
    return 0;
}
